# Generated by Django 2.2.5 on 2019-10-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0002_glass_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
