# Generated by Django 2.2.5 on 2019-10-12 20:49

import django.core.validators
from django.db import migrations, models
import glasses.models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0003_auto_20191004_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='glass',
            name='category',
            field=models.CharField(choices=[('UNDEFINED', 'Indéterminé'), ('WEDDING', 'Marriage'), ('BIRTHDAY', 'Anniversaire'), ('CHRISTMAS', 'Noël'), ('EASTER', 'Pâques')], default=glasses.models.GlassCategory('Indéterminé'), max_length=50),
        ),
        migrations.AlterField(
            model_name='glass',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='glass',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
