# Generated by Django 2.2.5 on 2019-10-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0004_auto_20191012_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glass',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
