# Generated by Django 2.2.5 on 2019-10-13 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0006_glass_creation_moment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glass',
            name='creation_moment',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
