# Generated by Django 2.2.5 on 2019-10-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0007_auto_20191013_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glass',
            name='category',
            field=models.CharField(blank=True, choices=[('UNDEFINED', 'Indéterminé'), ('WEDDING', 'Mariage'), ('BIRTHDAY', 'Anniversaire'), ('CHRISTMAS', 'Noël'), ('EASTER', 'Pâques')], max_length=50),
        ),
    ]
