# Generated by Django 2.2.5 on 2019-10-26 10:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import glasses.models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0008_auto_20191026_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='glass',
            name='category',
            field=models.CharField(blank=True, choices=[('UNDEFINED', 'Indéterminé'), ('WEDDING', 'Mariage'), ('BIRTHDAY', 'Anniversaire'), ('CHRISTMAS', 'Noël'), ('EASTER', 'Pâques')], default=glasses.models.GlassCategory('Indéterminé'), max_length=50),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('available_amount', models.PositiveIntegerField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('glasses', models.ManyToManyField(to='glasses.Glass')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='glasses.Supplier')),
            ],
        ),
    ]
